# Site settings
title: Juwai Engineering Blog
email: engineering@juwai.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome! not another Wordpress blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geeks.juwai.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: juwai

# Build settings
markdown: kramdown
